In [13]:
# Setup the environment
!pip install -q -U immutabledict sentencepiece 
!git clone https://github.com/google/gemma_pytorch.git
!mkdir /kaggle/working/gemma/
!mv /kaggle/working/gemma_pytorch/gemma/* /kaggle/working/gemma/

fatal: destination path 'gemma_pytorch' already exists and is not an empty directory.
mkdir: cannot create directory '/kaggle/working/gemma/': File exists
mv: cannot stat '/kaggle/working/gemma_pytorch/gemma/*': No such file or directory

In [14]:
import sys 
sys.path.append("/kaggle/working/gemma_pytorch/") 
from gemma.config import GemmaConfig, get_config_for_7b, get_config_for_2b
from gemma.model import GemmaForCausalLM
from gemma.tokenizer import Tokenizer
import contextlib
import os
import torch
import json
import random
import pandas as pd
import re

# Load the model
VARIANT = "7b-it-quant" 
MACHINE_TYPE = "cuda" 
weights_dir = '/kaggle/input/gemma/pytorch/7b-it-quant/2' 

@contextlib.contextmanager
def _set_default_tensor_type(dtype: torch.dtype):
  """Sets the default torch dtype to the given dtype."""
  torch.set_default_dtype(dtype)
  yield
  torch.set_default_dtype(torch.float)

model_config = get_config_for_2b() if "2b" in VARIANT else get_config_for_7b()
model_config.tokenizer = os.path.join(weights_dir, "tokenizer.model")
model_config.quant = "quant" in VARIANT

device = torch.device(MACHINE_TYPE)
with _set_default_tensor_type(model_config.get_dtype()):
  model = GemmaForCausalLM(model_config)
  ckpt_path = os.path.join(weights_dir, f'gemma-{VARIANT}.ckpt')
  model.load_weights(ckpt_path)
  model = model.to(device).eval()



# Use the model

USER_CHAT_TEMPLATE = "<start_of_turn>user\n{prompt}<end_of_turn>\n"
MODEL_CHAT_TEMPLATE = "<start_of_turn>model\n{prompt}<end_of_turn>\n"

prompt = (
    USER_CHAT_TEMPLATE.format(
        prompt="What is a good place for travel in the US?"
    )
    + MODEL_CHAT_TEMPLATE.format(prompt="California.")
    + USER_CHAT_TEMPLATE.format(prompt="What can I do in California?")
    + "<start_of_turn>model\n"
)

model.generate(
    USER_CHAT_TEMPLATE.format(prompt=prompt),
    device=device,
    output_len=100,
)

"There's a lot to see and do in California depending on your interests and preferred travel style. Here's a breakdown of a few popular options:\n\n**Classic Tourist Attractions:**\n\n* **San Francisco:** Golden Gate Bridge, Alcatraz Island, Fisherman's Wharf, Chinatown, Haight-Ashbury district, Golden Gate Bridge Trail (a scenic hike)\n* **Los Angeles:** Hollywood sign, Griffith Observatory, Universal Studios, Santa Monica Pier, Rodeo Drive, the Walk of Fame"

In [15]:
class PromptGenerator(object):
    def __init__(self):
        """
        Setup generation parameters for Gemma.
        """
        self.output_len = 25
        self.temperature = 0.0
        self.top_p = 1.0

    def create_prompt(self, sample):
        """
        Input sample is a dictionary consisting of following fields
        'table': A dict containing table data and meta-data same as in Assignment 2
        'question': A python string for the question on the table.
        
        The function must return the prompt as a python string.
        """
        # Example prompt
        prompt = """Read the following table and answer the related question based on the table.\n\n"""
        prompt += 'TABLE:\n'
        prompt += 'Header: '
        prompt += ','.join(
            [f'"{cc}"' for cc in sample['table']['cols']]
        ) + '\n'
        i=1
        for row in sample['table']['rows']:
            prompt += 'Row '+ str(i)+ ': '
            i+=1
            prompt += ','.join(
                [f'"{rr}"' for rr in row]
            ) + '\n'
        prompt += '\n'
        prompt += 'QUESTION: ' + sample['question'] + ' Include the column name and row number from the table to answer the question.' +'\n'

        return prompt
    
    def create_prompt_shot(self, sample):
        """
        Input sample is a dictionary consisting of following fields
        'table': A dict containing table data and meta-data same as in Assignment 2
        'question': A python string for the question on the table.
        
        The function must return the prompt as a python string.
        """
        # Example prompt
        prompt = """Read the following table and answer the related question based on the table.\n\n"""
        prompt += 'TABLE:\n'
        prompt += 'Header: '
        prompt += ','.join(
            [f'"{cc}"' for cc in sample['table']['cols']]
        ) + '\n'
        i=1
        for row in sample['table']['rows']:
            prompt += 'Row '+ str(i)+ ': '
            i+=1
            prompt += ','.join(
                [f'"{rr}"' for rr in row]
            ) + '\n'
        prompt += '\n'
        prompt += 'QUESTION: ' + sample['question'] + ' Include the column name and row number from the table to answer the question.' + '\n'
        prompt += "The column name is '" + sample['label_col'] + "' and the row number is " + sample['label_row'] + '\n'
        prompt += '\n'

        return prompt
    
    def post_process(self, gen_text):
        gen_text = gen_text.split("\n")[0]
        pattern = r"The column name is \'(.+?)\' and the row number is (\d+)"

        match = re.search(pattern, gen_text)

        if match:
                column_name = match.group(1)
                row_number = int(match.group(2))
                column_name = column_name.replace("'", "")
                row_number-=1
                return column_name, row_number
        else:
                # If no match is found, return None
                return None, None

In [16]:
sample_shot = {
    "question":"When was the opponent Poland and the match type EC -qualifier?",
    "table":{
        "cols":["Date","Location","Opponenent","Result","Match type"],
        "rows":[
            ["29 March 2000","Debrecen","Poland","0-0 (draw)","friendly"],
            ["16 August 2000","Budapest","Austria","1-1 (draw)","friendly"],
            ["3 September 2000","Budapest","Italy","2-2 (draw)","WC -qualifier"],
            ["15 August 2001","Budapest","Germany","2-5 (defeat)","friendly"],
            ["1 September 2001","Tbilisi","Georgia","1-3 (defeat)","WC-qualifier"],
            ["5 September 2001","Budapest","Romania","0-2 (defeat)","WC-qualifier"],
            ["6 October 2001","Parma","Italy","0-0 (draw)","WC-qualifier"],
            ["14 November 2001","Budapest","Macedonia","5-0 (win)","friendly"],
            ["12 February 2002","Larnaca","Czech Rep.","0-2 (defeat)","friendly"],
            ["13 February 2002","Limassol","Switzerland","1-2 (defeat)","friendly"],
            ["8 May 2002","P\u00e9cs","Croatia","0-2 (defeat)","friendly"],
            ["21 August 2002","Budapest","Spain","1-1 (draw)","friendly"],
            ["7 September 2002","Reykjav\u00edk","Iceland","2-0 (win)","friendly"],
            ["12 October 2002","Stockholm","Sweden","1-1 (draw)","EC-qualifier"],
            ["16 October 2002","Budapest","San Marino","3-0 (win)","EC -qualifier"],
            ["20 November 2002","Budapest","Moldova","1-1 (draw)","friendly"],
            ["12 February 2003","Larnaca","Bulgaria","0-1 (defeat)","friendly"],
            ["29 March 2003","Chorz\u00f3w","Poland","0-0 (draw)","EC -qualifier"],
            ["2 April 2003","Budapest","Sweden","1-2 (defeat)","EC -qualifier"],
            ["30 April 2003","Budapest","Luxembourg","5-1 (win)","friendly"],
            ["19 February 2004","Limassol","Latvia","2-1 (win)","friendly"],
            ["21 February 2004","Limassol","Romania","0-3 (defeat)","friendly"],
            ["9 February 2011","Dubai","Azerbaijan","2-0 (win)","friendly"],
            ["29 March 2011","Amsterdam","Netherlands","3-5 (defeat)","EC -qualifier"],
            ["3 June 2011","Luxembourg","Luxembourg","1-0 (win)","friendly"]
        ],
        "types":["text","text","text","text","text"],
        "caption":"National team matches",
    },
    "label_col":"Date",
    "label_row":"17"
}
sample_shot

sample_shot2 = {
    "question":"What is the total score when 7 is the average ranking?",
    "table":{
        "cols":["Average Ranking","Competitive Finish","Couple","Number Of Dances","Total Score","Average"],
        "rows":[
            ["1","1","Bridie & Craig","15","509","35.9"],
            ["2","3","David & Karina","12","360","30.0"],
            ["3","4","Patti & Sandro","10","295","29.5"],
            ["4","2","Anh & Luda","15","421","27.0"],
            ["5","9","Corinne & Csaba","3","77","25.7"],
            ["6","5","Mark & Linda","8","204","25.5"],
            ["7","8","Elka & Michael","4","100","25.0"],
            ["8","6","James & Olya","7","169","24.1"],
            ["9","7","Jessica & Serghei","5","120","24.0"]
        ],
        "types":["real","real","text","real","real","text"],
        "caption":"Average Chart"
    },
    "label_col":"Total Score",
    "label_row":"6"
}
# sample_shot2

# sample_shot3 = {
#     "question":"What was the largest crowd size at a South Melbourne home game?",
#     "table":{
#         "cols":["Home team","Home team score","Away team","Away team score","Venue","Crowd","Date"],
#         "rows":[
#             ["Melbourne","15.15 (105)","St Kilda","5.13 (43)","MCG","11,000","7 June 1947"],
#             ["Hawthorn","10.15 (75)","North Melbourne","10.11 (71)","Glenferrie Oval","12,000","7 June 1947"],
#             ["Carlton","16.21 (117)","Geelong","7.10 (52)","Princes Park","16,000","7 June 1947"],
#             ["South Melbourne","15.9 (99)","Richmond","15.13 (103)","Lake Oval","24,000","7 June 1947"],
#             ["Footscray","12.11 (83)","Fitzroy","7.7 (49)","Western Oval","20,000","7 June 1947"],
#             ["Essendon","9.14 (68)","Collingwood","11.16 (82)","Windy Hill","22,000","7 June 1947"]
#         ],
#         "types":["text","text","text","text","text","real","text"],
#         "caption":"Round 8"
#     },
#     "label_col":"Crowd",
#     "label_row":"3"
# }

In [17]:
# prompt_generator = PromptGenerator()
# prompt_shot = prompt_generator.create_prompt_shot(sample_shot)

In [18]:
# print(prompt_shot)

In [19]:
# samp = {
#     "question":"Which Attendance has an Arena of arrowhead pond of anaheim, and a Loss of giguere (3\u20133)?",
#     "table":{
#         "cols":["Date","Opponent","Score","Loss","Attendance","Series","Arena"],
#         "rows":[
#             ["May 19","Oilers","3\u20131","Bryzgalov (6\u20132)","17,174","0\u20131","Arrowhead Pond of Anaheim"],
#             ["May 21","Oilers","3\u20131","Bryzgalov (6\u20133)","17,264","0\u20132","Arrowhead Pond of Anaheim"],
#             ["May 23","@ Oilers","5\u20134","Bryzgalov (6\u20134)","16,839","0\u20133","Rexall Place"],
#             ["May 25","@ Oilers","6\u20133","Roloson (11\u20135)","16,839","1\u20133","Rexall Place"],
#             ["May 27","Oilers","2\u20131","Giguere (3\u20133)","17,174","1\u20134","Arrowhead Pond of Anaheim"]],
#         "types":["text","text","text","text","real","text","text"],
#         "caption":"Postseason",
#     }    
# }

# samp = {
#     "question":"What was the name for the row with Date From of 2008-02-21?",
#     "table":{
#         "cols":["Date From","Date To","Position","Name","From"],
#         "rows":[["2007-08-08","2007-08-13","GK","Chris Weale","Bristol City"],
#                 ["2007-08-10","End of season","MF","Toumani Diagouraga","Watford"],
#                 ["2007-08-10","End of season","FW","Theo Robinson","Watford"],
#                 ["2007-10-30","End of season","DF","Robbie Threlfall","Liverpool"],
#                 ["2007-11-16","End of season","DF","Lee Collins","Wolverhampton Wanderers"],
#                 ["2008-01-28","2008-04-30","FW","Gary Hooper","Southend United"],
#                 ["2008-02-08","2008-02-10","FW","Sherjill MacDonald","West Bromwich Albion"],
#                 ["2008-02-21","2008-03-24","MF","Stephen Gleeson","Wolverhampton Wanderers"],
#                 ["2008-03-27","2008-04-27","MF","Sammy Igoe","Bristol Rovers"]],
#         "types":["text","text","text","text","text"],
#         "caption":"Loan in"
#     }
# }

In [20]:
# prompt_generator = PromptGenerator()
# prompt_shot = prompt_generator.create_prompt_shot(sample_shot)
# prompt_shot2 = prompt_generator.create_prompt_shot(sample_shot2)
# # prompt_shot3 = prompt_generator.create_prompt_shot(sample_shot3)
# prompt_act = prompt_generator.create_prompt(samp)
# prompt = prompt_shot + prompt_shot2 + prompt_act
# print(prompt)
# answer = model.generate(
#     USER_CHAT_TEMPLATE.format(prompt=prompt),
#     device=device,
#     output_len=prompt_generator.output_len,
#     temperature=prompt_generator.temperature,
#     top_p=prompt_generator.top_p,
# )

In [21]:
# print(answer)

In [22]:
# sample = {
#     "question":"What is the sum of week(s) with an attendance of 30,751?",
#     "table":{
#         "cols":["Week","Date","Opponent","Result","Attendance"],
#         "rows":[
#             ["1","August 6, 1973","San Francisco 49ers","L 27\u201316","65,707"],
#             ["2","August 11, 1973","at Los Angeles Rams","T 21\u201321","54,385"],
#             ["3","August 19, 1973","vs. Cincinnati Bengals at Columbus, Ohio","W 24\u20136","73,421"],
#             ["4","August 25, 1973","vs. Atlanta Falcons at Knoxville","W 20\u201317","40,831"],
#             ["5","September 1, 1973","Detroit Lions","L 16\u201313","64,088"],
#             ["6","September 8, 1973","vs. New York Giants at Akron","L 21\u201310","30,751"]
#         ],
#         "types":["real","text","text","text","real"],
#         "caption":"Exhibition schedule"
#     }
# }
# sample
# prompt_gen = PromptGenerator()
# prompt_act = prompt_gen.create_prompt(sample)
# prompt_shot = prompt_gen.create_prompt_shot(sample_shot)
# prompt_shot2 = prompt_gen.create_prompt_shot(sample_shot2)
# prompt = prompt_shot + prompt_shot2 + prompt_act
# print(prompt)

# gen_text = model.generate(
#     USER_CHAT_TEMPLATE.format(prompt=prompt),
#     device=device,
#     output_len=prompt_gen.output_len,
#     temperature=prompt_gen.temperature,
#     top_p=prompt_gen.top_p,
# )

# print(gen_text)

# answer = prompt_gen.post_process(gen_text)
# answer

In [23]:
data = []
with open('/kaggle/input/a2-val/A2_val.jsonl', 'r') as f:
    for line in f:
        data.append(json.loads(line))

# Sample 100 random samples
random.seed(42)
samples = random.sample(data, 100)

In [24]:
# Generate the answers
prompt_generator = PromptGenerator()
prompt_shot = prompt_generator.create_prompt_shot(sample_shot)
prompt_shot2 = prompt_generator.create_prompt_shot(sample_shot2)
# prompt_shot3 = prompt_generator.create_prompt_shot(sample_shot3)
col_answers = []
row_answers = []
num=1
maxrow=0
for sample in samples:
    print("Sample number is "+ str(num))
    print("Question is "+ sample['question'])
    if len(sample['table']['rows']) > 100:
        sample['table']['rows'] = sample['table']['rows'][:100]
    cur_sample = {'question': sample['question'], 'table': sample['table']}
    maxrow = max(maxrow,len(sample['table']['rows']))
    prompt_act = prompt_generator.create_prompt(cur_sample)
    prompt = prompt_shot + prompt_shot2 + prompt_act
    answer = model.generate(
        USER_CHAT_TEMPLATE.format(prompt=prompt),
        device=device,
        output_len=prompt_generator.output_len,
        temperature=prompt_generator.temperature,
        top_p=prompt_generator.top_p,
    )
    answer_pair = prompt_generator.post_process(answer)
    print(answer)
    print(answer_pair)
    print("Column should be "+ sample['label_col'][0])
    print("Row should be "+ ', '.join([str(rr) for rr in sample['label_row']]))
    print("===================================================================")
    col_answers.append(answer_pair[0])
    row_answers.append(answer_pair[1])
    num+=1
    del cur_sample
    del prompt_act
    del prompt
    del answer
    del answer_pair

# Now find the accuracy of the model
correct_col = 0
correct_row = 0
for sample, answer in zip(samples, col_answers):
    if sample['label_col'][0] == answer:
        correct_col += 1
for sample, answer in zip(samples, row_answers):
    if sample['label_row'][0] == answer:
        correct_row += 1
col_acc = correct_col / len(samples)
row_acc = correct_row / len(samples)
# print("Column acc is " + col_acc)
# print("Row acc is " + row_acc)
# accuracy = correct / len(samples)
# print("accuracy is "+ accuracy)
# print("maxrow is "+ maxrow)
# print("correct ans is "+ correct)

Sample number is 1
Question is Who is Winners that has  editions of 1992, 2003 as Not Winning
The column name is 'Winners' and the row number is 2

**Please answer the questions below:**

**1
('Winners', 1)
Column should be Winners
Row should be 1
===================================================================
Sample number is 2
Question is What was the name for the row with Date From of 2008-02-21?
The column name is 'Name' and the row number is 8

**Please answer the questions below based on the text
('Name', 7)
Column should be Name
Row should be 7
===================================================================
Sample number is 3
Question is What's listed as the First Day Cover Cancellation with a Date of Issue of 13 June 2005?
The column name is 'First Day Cover Cancellation' and the row number is 15

**Please answer the question based
('First Day Cover Cancellation', 14)
Column should be First Day Cover Cancellation
Row should be 14, 15
===================================================================
Sample number is 4
Question is what is the nme of the song performed by billy vaughn?
The column name is 'Song title' and the row number is 4

**Please answer the questions based on the provided
('Song title', 3)
Column should be Song title
Row should be 3
===================================================================
Sample number is 5
Question is Which Driver has a Sponsor of pdvsa?
The column name is 'Sponsor(s)' and the row number is 5

**Please answer the questions based on the
('Sponsor(s)', 4)
Column should be Driver(s)
Row should be 4
===================================================================
Sample number is 6
Question is What home team played against St Kilda?
The column name is 'Home team' and the row number is 1

**Answer the question:**

**The text
('Home team', 0)
Column should be Home team
Row should be 0
===================================================================
Sample number is 7
Question is I want the highest Grid for Toyota and jarno trulli
The column name is 'Grid' and the row number is 3

**Please answer the questions based on the text.**
('Grid', 2)
Column should be Grid
Row should be 12
===================================================================
Sample number is 8
Question is What was the attendance for each game held at Foxboro Stadium?
The column name is 'Attendance' and the row number is 7

**Answer:**

**The answer to the first
('Attendance', 6)
Column should be Attendance
Row should be 6
===================================================================
Sample number is 9
Question is What term did hon ralph hunt serve in office?
The column name is 'Term in office' and the row number is 66
('Term in office', 65)
Column should be Term in office
Row should be 65
===================================================================
Sample number is 10
Question is What is the sum of yards for a 118.7 rating?
The column name is 'Yards' and the row number is 6

**Please answer the questions based on the provided
('Yards', 5)
Column should be Yards
Row should be 5
===================================================================
Sample number is 11
Question is What is the roll of Bishop Viard College (An Integrated College), which has a decile larger than 1?
The column name is 'Roll' and the row number is 3

**Please answer the questions based on the above text
('Roll', 2)
Column should be Roll
Row should be 2
===================================================================
Sample number is 12
Question is Can you tell me the lowest Total natches that has the Points won of 3, and the Year of 1994?
The column name is 'Total matches' and the row number is 3

**Answer the question below:**

The table
('Total matches', 2)
Column should be Total matches
Row should be 3
===================================================================
Sample number is 13
Question is Name the period for Chart of g-music j-pop/k-pop chart
The column name is 'Period' and the row number is 6

**Answer:**

**The answer to the first
('Period', 5)
Column should be Period
Row should be 5
===================================================================
Sample number is 14
Question is What is the Catalog number in the Region of France?
The column name is 'Catalog' and the row number is 1

**Answer the questions based on the provided text.**
('Catalog', 0)
Column should be Catalog
Row should be 0, 1, 2, 3, 4
===================================================================
Sample number is 15
Question is What percent of others did ogm/news count when MARTIN had 9%?
The column name is 'Others' and the row number is 10

**Please answer the questions based on the provided
('Others', 9)
Column should be Others
Row should be 9
===================================================================
Sample number is 16
Question is When 10% is the percentage of electricity reduction how many sets of universities are there?
The column name is 'No. of Students Signed up' and the row number is 1

**Please answer the question
('No. of Students Signed up', 0)
Column should be Universities
Row should be 0
===================================================================
Sample number is 17
Question is Which party is sydney sampson a member of?
The column name is 'Party' and the row number is 60

**Please answer the questions based on the provided
('Party', 59)
Column should be Party
Row should be 59
===================================================================
Sample number is 18
Question is When was the event that had Liberia as an opponent and resulted in a 1-0 score?
The column name is 'Date' and the row number is 2

The text below provides a list of information about various
('Date', 1)
Column should be Date
Row should be 1
===================================================================
Sample number is 19
Question is How many conflicts started in Afghanistan?
The column name is 'Start of conflict' and the row number is 2

**Answer:**

**The answer to
('Start of conflict', 1)
Column should be Start of conflict
Row should be 4
===================================================================
Sample number is 20
Question is Where were the Womens Doubles in the 1951/1952 season and who won?
The column name is 'Womens Doubles' and the row number is 14

**Please answer the questions based on
('Womens Doubles', 13)
Column should be Womens doubles
Row should be 13
===================================================================
Sample number is 21
Question is what is the mascot for the enrollment 08-09 of 320?
The column name is 'Mascot' and the row number is 6

**Please answer the question based on the text
('Mascot', 5)
Column should be Mascot
Row should be 5
===================================================================
Sample number is 22
Question is Tell me the sum of original week for september 16, 1982
The column name is 'Original week' and the row number is 2

**Please answer the questions based on the provided
('Original week', 1)
Column should be Original week
Row should be 1
===================================================================
Sample number is 23
Question is Who was the winning driver of the Savio Circuit with the constructor Itala?
The column name is 'Winning driver' and the row number is 7

**Please answer the question based on the text
('Winning driver', 6)
Column should be Winning driver
Row should be 6
===================================================================
Sample number is 24
Question is What was the date when the Twins had a record of 44-37?
The column name is 'Date' and the row number is 28

**Please answer the questions based on the provided
('Date', 27)
Column should be Date
Row should be 25
===================================================================
Sample number is 25
Question is Which Chassis was featured in the year 1971?
The column name is 'Chassis' and the row number is 1

**Please answer the question below:**

Which year
('Chassis', 0)
Column should be Chassis
Row should be 0, 1
===================================================================
Sample number is 26
Question is What is the attendance for the t7-7 result?
The column name is 'Attendance' and the row number is 3

**Answer the questions below:**

**1.**
('Attendance', 2)
Column should be Attendance
Row should be 2
===================================================================
Sample number is 27
Question is Which Venue has a Home team of essendon?
The column name is 'Venue' and the row number is 2

**Please answer the questions based on the text above
('Venue', 1)
Column should be Venue
Row should be 1
===================================================================
Sample number is 28
Question is What was the qualifying score of the competition whose final score was 12.200?
The column name is 'Score-Qualifying' and the row number is 6

**Please answer the questions below based
('Score-Qualifying', 5)
Column should be Score-Qualifying
Row should be 5
===================================================================
Sample number is 29
Question is Which Year has a Regular Season of 7th?
The column name is 'Regular Season' and the row number is 2

**Please answer the questions based on the text
('Regular Season', 1)
Column should be The Year
Row should be 4
===================================================================
Sample number is 30
Question is Which Title is from 1952?
The column name is 'Title' and the row number is 16

**Please answer the questions based on the provided
('Title', 15)
Column should be Title
Row should be 15
===================================================================
Sample number is 31
Question is What rank is associated with Germany?
The column name is 'Rank' and the row number is 6

**Answer:**

**The answer to the first
('Rank', 5)
Column should be Rank
Row should be 6
===================================================================
Sample number is 32
Question is Name the position of pick 234
The column name is 'Position' and the row number is 26

**Please answer the questions based on the text
('Position', 25)
Column should be Position
Row should be 25
===================================================================
Sample number is 33
Question is Which Position has a Team from of ottawa 67's, and a Pick # smaller than 47?
The column name is 'Position' and the row number is 2

The text does not contain any information about the text
('Position', 1)
Column should be Position
Row should be 3
===================================================================
Sample number is 34
Question is What is the no party preference when republican is 45.3%?
The column name is 'No party preference' and the row number is 24

**Please answer the questions based on
('No party preference', 23)
Column should be No party preference
Row should be 23
===================================================================
Sample number is 35
Question is On what date was the record with catalog ALCA-275 released?
The column name is 'Date' and the row number is 4

**Please answer the questions below:**

**1
('Date', 3)
Column should be Date
Row should be 3
===================================================================
Sample number is 36
Question is When ratkovo is the settlement what is the cyrllic name other names?
The column name is 'Cyrillic Name Other Names' and the row number is 4

**Answer the questions below:**
('Cyrillic Name Other Names', 3)
Column should be Cyrillic Name Other Names
Row should be 7
===================================================================
Sample number is 37
Question is What is the record on January 18?
The column name is 'Record' and the row number is 8

**Please answer the question based on the provided text
('Record', 7)
Column should be Record
Row should be 8
===================================================================
Sample number is 38
Question is Name the least dismissals for sammy carter
The column name is 'Dismissals' and the row number is 8

**Please answer the question based on the text
('Dismissals', 7)
Column should be Dismissals
Row should be 7
===================================================================
Sample number is 39
Question is What's Bulgaria's lane?
The column name is 'Lane' and the row number is 30

**Please answer the questions based on the provided
('Lane', 29)
Column should be Lane
Row should be 29
===================================================================
Sample number is 40
Question is What Country is Player Leland Gibson with Money of 400 from?
The column name is 'Country' and the row number is 6

**Answer the questions below:**

**1.**
('Country', 5)
Column should be Country
Row should be 7
===================================================================
Sample number is 41
Question is What is the highest Points with a Lost total of 8?
The column name is 'Points' and the row number is 2

**Answer the questions based on the provided text.**
('Points', 1)
Column should be Points
Row should be 4
===================================================================
Sample number is 42
Question is what is the party for district ohio 11?
The column name is 'Party' and the row number is 6

**Answer the questions based on the provided text.**
('Party', 5)
Column should be Party
Row should be 6
===================================================================
Sample number is 43
Question is Name the sarasota samantha sharpe
The column name is 'Sarasota' and the row number is 12

**Please answer the questions based on
('Sarasota', 11)
Column should be Sarasota
Row should be 12
===================================================================
Sample number is 44
Question is What day did the platform sell 9.87 million units?
The column name is 'Release Date' and the row number is 9

**Answer the questions below:**

**1
('Release Date', 8)
Column should be Release Date
Row should be 8
===================================================================
Sample number is 45
Question is how many times was third place held by drnovice?
The column name is 'Third Place' and the row number is 2

The text does not contain any information about the
('Third Place', 1)
Column should be Club
Row should be 6
===================================================================
Sample number is 46
Question is What is the average attendance of the team that had a regular season result of 2nd aisa, 24-16?
The column name is 'Attendance Average' and the row number is 5

**Please answer the question based on the text
('Attendance Average', 4)
Column should be Attendance Average
Row should be 4
===================================================================
Sample number is 47
Question is Which country has a score of 73-74-69=216?
The column name is 'Score' and the row number is 9

**Please answer the questions based on the provided text
('Score', 8)
Column should be Country
Row should be 9
===================================================================
Sample number is 48
Question is With a date of May 1262 under elevated, Guillaume de Bray as the elector, what is the order and title?
The column name is 'Order and title' and the row number is 4

**Please answer the questions based on the
('Order and title', 3)
Column should be Order and title
Row should be 4
===================================================================
Sample number is 49
Question is When did the part 1 of the episode "Anxiety" air?
The column name is 'Part 1' and the row number is 3

**Please answer the question based on the
('Part 1', 2)
Column should be Part 1
Row should be 2
===================================================================
Sample number is 50
Question is What is the second stage that has the third phase of 20kn?
The column name is '2nd stage' and the row number is 3

**Please answer the questions based on the
('2nd stage', 2)
Column should be 2nd stage
Row should be 2
===================================================================
Sample number is 51
Question is When was the earliest year that Guillermo Vilas was the runner-up?
The column name is 'Year' and the row number is 10

**Please answer the questions below:**

**
('Year', 9)
Column should be Year
Row should be 9
===================================================================
Sample number is 52
Question is What is the date (to) associated wiht a traction type of electric and the Yarmouth Light and Power Company system?
The column name is 'Date (To)' and the row number is 8

**Please answer the questions below based on
('Date (To)', 7)
Column should be Date (To)
Row should be 7
===================================================================
Sample number is 53
Question is What tournament was on May 31, 1987?
The column name is 'Tournament' and the row number is 2

**Answer:**

**The answer to the first
('Tournament', 1)
Column should be Tournament
Row should be 1
===================================================================
Sample number is 54
Question is What is the launch site of the delta iv rocket?
The column name is 'Launch site' and the row number is 1

**Answer the questions below:**

**1
('Launch site', 0)
Column should be Launch site
Row should be 0, 1, 4, 5
===================================================================
Sample number is 55
Question is How many party classifications are there for the senator from Canton?
The column name is 'Party' and the row number is 29

**Please answer the questions based on the provided
('Party', 28)
Column should be Party
Row should be 28
===================================================================
Sample number is 56
Question is Which swimmer has a 100m time longer than 57.34 and a 600m of 5:54.45?
The column name is 'Time' and the row number is 2

**Answer:**

**The answer to the first
('Time', 1)
Column should be 200m
Row should be 1
===================================================================
Sample number is 57
Question is What is the name of the venue where home team st kilda played?
The column name is 'Venue' and the row number is 5

**Please answer the question below:**

What is
('Venue', 4)
Column should be Venue
Row should be 4
===================================================================
Sample number is 58
Question is What was the score that made the record 47-49?
The column name is 'Score' and the row number is 18

**Please answer the questions based on the provided
('Score', 17)
Column should be Score
Row should be 17
===================================================================
Sample number is 59
Question is What Date was the Game at Griffith Stadium?
The column name is 'Date' and the row number is 3

**Please answer the questions based on the text above
('Date', 2)
Column should be Date
Row should be 2
===================================================================
Sample number is 60
Question is Which game number did they play the Chicago team?
The column name is 'Game' and the row number is 6

**Please answer the questions based on the provided text
('Game', 5)
Column should be Game
Row should be 5
===================================================================
Sample number is 61
Question is Which school/club team has a player named Mark Sanford?
The column name is 'School/Club Team' and the row number is 3

**Please answer the question based on
('School/Club Team', 2)
Column should be School/Club Team
Row should be 2
===================================================================
Sample number is 62
Question is How many blocks does the player who played 893 minutes have?
The column name is 'Blocks' and the row number is 3

**Please answer the questions based on the text above
('Blocks', 2)
Column should be Blocks
Row should be 2
===================================================================
Sample number is 63
Question is Opponent of @ blue jays, and a Loss of lyon (5-4) had what opponent?
The column name is 'Score' and the row number is 2


In [25]:
print(col_acc)
print(row_acc)

0.84
0.7

In [26]:
print(correct)

NameError: name 'correct' is not defined